version: "3"

services:
  # Serviço que irá rodar o node
  
  db:
    container_name: store_manager_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # Garanta que não haverá conflitos de porta com um banco que esteja
      # rodando localmente
      - ${MYSQL_PORT}:${MYSQL_PORT}